### ISSUE TITLE
Customising the dashboard widget

### ISSUE THREAD

**Issue by simonjohnparker** [TechToThePeople/civisualize#104]
Hi (non-coder here),

Love this extension but I'm trying to get the dashboard widget to just show only current FY April - March. 

Any guidance on how to this?

Thanks!

**Comment by tttp** [comment]
Hi simon,

civisualize provides several dashlets, which ones is the one you're using?

**Comment by simonjohnparker** [comment]
Hi @tttp thanks for coming back to me.

I'm not entirely sure, just the default one when I installed the extension? How would I change the dashlet and see what others are available?

Thanks!

**Comment by simonjohnparker** [comment]
Hi @tttp this was closed but I didn't get an answer to the question?

Thanks,
