### ISSUE TITLE
JavaScript error civisualize-bundle Unexpected token '}'

### ISSUE THREAD

**Issue by Nicholas-hosein-pw** [TechToThePeople/civisualize#112]
Hi,

After adding Civisualize to my site I tried to open the default visualizations but when the page loaded none of the data showed up and there was a JavaScript error.

JavaScript error:
*civisualize-bundle.e2342d8f6da25e9c0252b878e7997e7a.js*:12 **Uncaught SyntaxError: Unexpected token '}'**

line 12 starts like:
```javascript
else this._+='L'+(this._x1=t)+','+(this._y1=n);else},arc:function
```

It seems that the error is at the "**else}**". I believe the error is coming from the file:
*eu.tttp.civisualize/js/d3.min.v5.7.0.js*
at the part like: "**else;}​​​​​,arc:function**", I think there is something that is removing the semicolon when the civisualize-bundle file is created.

**Comment by tttp** [comment]
Hi,

is this your CMS that bundle the js files together? Could you try to
disable that feature to see if it works?

**Comment by Nicholas-hosein-pw** [comment]
I think we tried that already.
We are using Drupal 7, we went to the Configuration>Development>Performance setting and turned off "Aggregate JavaScript files".

**Comment by tttp** [comment]
and you still have the error message on civisualize-bundle.e2342d8f6da25e9c0252b878e7997e7a.js ?

**Comment by Nicholas-hosein-pw** [comment]
Hi,

Just an update, we noticed that there was a different civi extension that was minifying the js.
CSS/JS minifier for AssetBuilder (minifier)
Once we turned that off the visualization pages started working.

Thanks for your replies. : )
