### ISSUE TITLE
PHP Fatal error on php 8+

### ISSUE THREAD

**Issue by calbasi** [TechToThePeople/civisualize#119]
I get this error if using php 8.0 or php 8.1:

> [Fri Sep 09 12:07:16.910837 2022] [fcgid:warn] [pid 125734:tid 140482680891136] [client 139.47.120.77:26413] mod_fcgid: stderr: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/XXX/web/sites/default/civicrm_extensions/eu.tttp.civisualize/civisualize.civix.php on line 247, referer: https://XXX.xyz/es

**Comment by wmortada** [comment]
Are you using the latest code from the master branch? I think this may have been fixed in #115.

If that doesn't fix it you may need to regenerate `civix` again. `civix` is a command line utility that is used to generate boilerplate code for CiviCRM modules (see https://github.com/totten/civix).

**Comment by calbasi** [comment]
I've tried it again, using Civicrm extension page to install it (there is version 6.0 available) and I get this error again.

I'm going to check the Civix stuff later... I try to post here my feedback

**Comment by wmortada** [comment]
Version 6 is quite out of date now (June 2020). Try the master branch for the latest code.

**Comment by calbasi** [comment]
Is it possible to use the master branch from the Extension management UI?

**Comment by wmortada** [comment]
I'm afraid not but you can download it here: https://github.com/TechToThePeople/civisualize/archive/refs/heads/master.zip

**Comment by calbasi** [comment]
That's OK with master branch (version 6.1 ?) I wonder if it would be time to deploy it as the last stable version, to avoid this issue in other users that just use the extension management system built-in on CiviCRM.

**Comment by wmortada** [comment]
Yup, that would be good. @tttp could you create a new release?

**Comment by mlutfy** [comment]
@tttp Could you tag a release, or give me access to do it? (I can also move the extension to Gitlab, if you'd like)

We're doing a push for PHP 8 compatibility: https://civicrm.org/blog/bgm/php-8-support-civicrm-extensions

**Comment by tttp** [comment]
Hi @mlutfy, I've added you. 

if you find it easier, you can move the extension to gitlab too

**Comment by mlutfy** [comment]
Thank you @tttp ! I moved it here: https://lab.civicrm.org/extensions/civisualize/-/issues and added you as maintainer. I will disable issues here and update the README and other references.

**Comment by mlutfy** [comment]
Version 6.1 has been published: https://civicrm.org/extensions/civisualize-missing-data-visualization-extension
