### ISSUE TITLE
Joomla integration: Could not find valid value for q

### ISSUE THREAD

**Issue by magnolia61** [TechToThePeople/civisualize#28]
When I try to use the dataviz extension on our civicrm 4.4.6 site on joomla using:
administrator/?option=com_civicrm&task=civicrm/dataviz/contribute
we get a fatal error stating:
    Sorry but we are not able to provide this at the moment.
    Could not find valid value for q
    Return to home page.
Is the extension currently drupal only or is this a small quick fixable quirk for you?

**Comment by RandyTobias** [comment]
This can be resolved by opening http://www.yourdomain.com/media/civicrm/extensions/civisualize-1.0/CRM/Civisualize/Page/Main.php and making the following change:

- $request = CRM_Utils_Request::retrieve( 'q', 'String',$dummy, true, NULL, 'GET');
+$request = CRM_Utils_Request::retrieve( 'task', 'String',$dummy, true, NULL, 'GET');

**Comment by tttp** [comment]
Fixed on git: it uses the generic function CRM_Utils_System::currentPath()

X+
