### ISSUE TITLE
Civisualize dashlets disappears

### ISSUE THREAD

**Issue by knockiiing** [TechToThePeople/civisualize#48]
Hi, 
When a civisualize dashlet is closed from "configure dashboard" area it disappears. How can we make it again available in the "configure dashboard" area so that users can select them for their dashboard? Many thanks,
Patrick

**Comment by awestbha** [comment]
Does it come back if you completely disable and then re-enable the extension?

**Comment by shawnholt** [comment]
Double check permissions and logfile.
