### ISSUE TITLE
add sanity check to warn if extension url isn't properly set up

### ISSUE THREAD

**Issue by tttp** [TechToThePeople/civisualize#61]
It seems it's a common pattern that the extension url isn't properly configured, so we don't load properly the d3 and dc and pals

It leads to a dataviz that is mostly empty, with no graph. Instead of expecting the users to check if there is a js error ("dc not an object" type), let's test it and display a proper error message

X+

**Comment by vmantese** [comment]
People probably incorrectly formatted their resources URL: ie used a windows native C:\..... format which causes the js to not be loaded.
I agree that a quick check on this might be helpful

**Comment by siddharthg** [comment]
@tttp is there any particular way to achieve this? I think one place can be where we include these files.

**Comment by tttp** [comment]
The easiest is probably to start with a check that

    if (typeof dc == "undefined") {
      CRM.error ("Something is wrong in your configuration, check that the
url for extensions is properly set up");
      return;
    }

**Comment by vmantese** [comment]
Short and sweet.
