### ISSUE TITLE
Dynamically get labels from option groups

### ISSUE THREAD

**Issue by RandyTobias** [TechToThePeople/civisualize#63]
I think it would make sense to dynamically get labels from option groups. For example, I was trying out the contribution trends sample and found that genderLabel was set to {1:"Male", 2:"Female"}. I ended up changing it to {1:"Female",2:"Male",3:"Transgender"} to match my civicrm option group. 

I'm aware that this was just a sample. That said, it would be nice if there was built in functionality for this kind of thing. Another example would be to make date formats match the setting specified in Civicrm. I feel that changes like these would really help to integrate the data visualizations with Civicrm and make the extension much more robust.

It is an excellent extension as it is.

**Comment by tttp** [comment]
Hi, @siddharthg has worked to get the options from the db already (for the next version, coming soon)

**Comment by RandyTobias** [comment]
Sounds great! Thanks for your quick reply.

Side note: I wasn't sure how to add the enhancement label to the post.
