### ISSUE TITLE
4.6 ready?

### ISSUE THREAD

**Issue by magnolia61** [TechToThePeople/civisualize#65]
With the 4.6 in beta since today i was wondering, do you foresee any issues with compatibility (or would you think this extension will have nog big issues working in 4.6? Of course I will also try and test myself, but you know the architecture of the extension and changes in civicrm better than I do :-)

**Comment by tttp** [comment]
Hi,

I see no reason why it wouldn't work... but testers welcome

**Comment by colemanw** [comment]
http://civicrm.stackexchange.com/questions/4927/is-civisualize-compatible-with-4-6

**Comment by colemanw** [comment]
Would be great to get a release tagged as 4.6-compat.
