### ISSUE TITLE
Please add copyright statement and license.

### ISSUE THREAD

**Issue by onlyjob** [TechToThePeople/civisualize#66]
Please add copyright statement and license.
Ideally it would be great if you use an AGPL-3+ compatible license,
perhaps (A)GPL-3+, MIT (Expat) or Apache-2.0.
Thanks.

**Comment by tttp** [comment]
agpl indeed, i need to add it, thanks

**Comment by tttp** [comment]
added the link to civicrm licence in info.xml, so agpl3
