### ISSUE TITLE
Civizualize does not render visualizations

### ISSUE THREAD

**Issue by Corvalan** [TechToThePeople/civisualize#68]
Using Civicrm 4.6.5 and the latest master branch of Civizualize at github https://github.com/TechToThePeople/civisualize, The page /civicrm/dataviz shows the default visualizations list, but when I click on one of them, the vizualization does not render.
For screenshots, see http://civicrm.stackexchange.com/questions/4577/civizualize-does-not-render

**Comment by tttp** [comment]
Probably a configuration error or error on another javascript code. I close the issue here, we can continue on stackexchange
