### ISSUE TITLE
Unable to modify civisualize permissions: allows open access!

### ISSUE THREAD

**Issue by vmantese** [TechToThePeople/civisualize#72]
I've been unable to restrict access to civisualize. I tried altering the Menu file in civisualize/xml/Menu/civizualize.xml but it still seemed that anyone with access to civicrm could access the main page. This is a problem because Civisualize is able to pull data from across the database and users could see dashboards that they shouldn't. Is anyone able to restrict access to the dashboards?

**Comment by vmantese** [comment]
I was able to solve this problem but it requires a large amount of rewriting across the repository. I think it stems from the fact that the module confuses civizualize, civisualize, and civizualise quite frequently. 
I renamed the repository in the traditional manner.

Summary of edits...


Renamed containing file to eu.tttp.civisualize
Changed all instances of civizualize, civisualize, and civizualize to **civisualize**
Changed all instances of dataviz to civisualize

Corrected the first hook in the civisualize.php file from civicrm_civicrm_dashboard( $contactID, &$contentPlacement ) to **civisualize_civicrm_dashboard( $contactID, &$contentPlacement ) **

These changes worked, now Civisualize is not exposed. Before anyone with access to CiviCRM could access any dashboard regardless of their underlying permissions. By making the above edits we are at least able to add a gateway, now you can restrict anyone from accessing any Civisualize pages by using the xml file eu.ttp.civisualize/xml/Menu/civizualize.xml (note the changed containing folder name)

**Comment by tttp** [comment]
Hi Vito,

Indeed, the dataviz is open to every civicrm user, the rationale for that is no individual information is provided, just individual ones.

During a GSoC, @siddharthg worked on trying to introduce finer control on a per viz base, but don't recall the result. @siddharthg could you update us?

If there is a typo and there is civizualize somewhere, of course it is a typo and needs to be changed, thanks of spotting them (same goes for the extra z)!

For the change from dataviz to civisualize: it was a choice to keep the urls nicer looking, and the template folders followed the same convention. It's a subjective one, no point to argue about which one is best, but it has nothing to do with access control. 
I feel hey are too many dependent extensions that will break and too many links in navigation menues that I don't want to make that change.

But what you did to change the access right from access CiviCRM to access report is the right move, I think. I have no idea how to test with folks, but let's go with it and see what happens.

Could you do a new PR with just the typo fixes and change of access so I can properly credit you in the log change?

If you don't have the time, @siddharthg, could you ask your student as part of the community bonding to have a look?

**Comment by siddharthg** [comment]
We worked on the overall extension being private or public but not per extension as such. I can take it up or will ask @Anjali2906 to take it up.

**Comment by vmantese** [comment]
I'm happy to rebranch it and just standardize the civisualize section  and hook change while leaving the other parts alone. To get back to the rationale, I frequently use the dataTable visualization which often displays individual's information. It's a great way to show specifics alongside a nice bar-chart etc... For now I'll just change the permission level to 'access CiviReport' but I would propose also giving the option to create a new permission (using hook_civicrm_permission(&$permissions)) and then allowing users to specify groups to whom they will apply those permissions. Just a thought, my rewritten PR will not include this.
