### ISSUE TITLE
'var data' clashes with other javascript

### ISSUE THREAD

**Issue by rocxa** [TechToThePeople/civisualize#76]
We have found that the variable

**var data**        = {crmSQL file="donors"}; etc 

clashes with other modules that also use a variable named 'data'

To get CiviVisualise working we have renamed all 'data' variables to 'data_viz'

Once I know which other JavaScript is clashing with CiviVisualize, i'll comment again here.

**Comment by rocxa** [comment]
The data variable gets broken between line 105 of Events.tpl and line 110.  It also happens in other civivisualise tpl files but not all of them.

-------

console.log('3');
console.log(data);  //data OK       
    
var eventsBar, upcomingNumber, pastNumber, participantsLine, typePie, startdayRow, eventStatusPie, monetoryPie, dataTable;

cj(function($) {  // this changes the scope and it breaks

console.log('3.5');
console.log(data);`  // data has some drupal views plugins in it instead...

---------

The culprit of the clash appears to be slick nav which is part of 'Administration menu Adminimal Theme' https://www.drupal.org/project/adminimal_admin_menu

**Comment by tttp** [comment]
Hi,
we could/should wrap all our code into an anonymous function, but I find them a bit of a pain to debug. thought?

**Comment by tttp** [comment]
No response, I'm closing, feel free to re-open
