### ISSUE TITLE
Mailings  Broken

### ISSUE THREAD

**Issue by erogers** [TechToThePeople/civisualize#80]
Recently this extension and started trying it out. The parts work are great! On my setup the Mailings  report is empty. Screenshot attached.  I'm running Civi 4.7.10 on WordPress 4.6.
![screenshot 2016-08-26 14 39 11](https://cloud.githubusercontent.com/assets/830171/18018149/e161e48a-6b9a-11e6-9301-2db96bf1cef3.png)

**Comment by tttp** [comment]
I need to push an update, should be fixed next week

**Comment by daniellaveda** [comment]
Hello,

Are you able to share any info on when this will be resolved as we still have users experiencing issues using Mailings with CiviVisulize

Many thanks
