### ISSUE TITLE
How to supply user input to custom visualizations?

### ISSUE THREAD

**Issue by seanmadsen** [TechToThePeople/civisualize#84]
I'd like to make a custom visualization with Civisualize but the visualization requires the user to first provide some input through several form elements. None of the visualizations that I see within Civisualize allow for any user input. Is this possible with Civisualize?

I also posted [this question on Stack Exchange](http://civicrm.stackexchange.com/questions/17142/how-to-supply-user-input-to-custom-visualizations-with-civisualize).

**Comment by tttp** [comment]
Ok, le'ts move the discussion on stackexchange
