### ISSUE TITLE
If we deleted the civisualize dashlet in Dashboard, it will create a problem.

### ISSUE THREAD

**Issue by prakashmtl** [TechToThePeople/civisualize#88]
By mistake, if we deleted the dashlet (Civisualize) in civicrm dashboard, then we cannot able to disable/enable any extension. It gives an error. 
![image](https://user-images.githubusercontent.com/31104162/29977580-ce15335e-8f35-11e7-8f8a-3c9c69301799.png)

**Comment by tttp** [comment]
Hi,

Can you enable the debug/backtrace display and paste the detail of the error?

**Comment by prakashmtl** [comment]
![image](https://user-images.githubusercontent.com/31104162/29977982-40b16df0-8f37-11e7-878a-5d997eac77bc.png)

**Comment by mattwire** [comment]
I hit this too, same issue.  The actual failure is a DB constraint error:
```INSERT INTO civicrm_dashboard_contact ( dashboard_id, contact_id )
                  VALUES  ( 15, 1 ), ( 15, 82 ),...```
As dashboard id=15 doesn't exist we fail a foreign key constraint and crash.

I worked around by created an entry in civicrm_dashboard with id=15 which then allowed civisualise to install without error and overwrite dashboard 15 with it's own values.

**Comment by galgeek** [comment]
I've hit this error, too.

Only the civicrm_dashboard id is different. ;)
