### ISSUE TITLE
Change 'monetory' to 'paid'

### ISSUE THREAD

**Issue by wmortada** [TechToThePeople/civisualize#89]
Thanks for developing a great extension! I have a minor suggestion to improve the language used in one of the reports.

The events visualisation report contains a graph titled: 'Is Monetory?'   This is spelled incorrectly.  It should be 'monetary' rather than 'monetory'.  But rather than just correct the spelling, I would suggest that it would be better to change the title to 'Paid event' and change the other occurrences of 'monetory' to 'paid' throughout this report.  I think that is simpler and clearer language.

**Comment by tttp** [comment]
Hi @wmortada, great suggestion, could you edit the tpl file and do a PR?

**Comment by wmortada** [comment]
Yes, I'd be happy to have a look at this during the CiviCRM Sprint.

**Comment by wmortada** [comment]
Sorry, I didn't get a chance to look at this during the sprint.  Hope to have a look at it over the coming weeks if I have time.
