### ISSUE TITLE
NULL as a date causes problems

### ISSUE THREAD

**Issue by petednz** [TechToThePeople/civisualize#91]
Not sure how easy this is to fix - but we spotted on some sites they somehow had NULL date for a Contribution and that throws the x-axis back to year dot

also the year on the axis shows with a comma which is not ideal

**Comment by tttp** [comment]
well, if you have a contribution with NULL as a date, you might have other problems than the dataviz ;)

This being said, if the aim is to "simply" hide them, adding a "AND date is not NULL" on the sql should "fix" it. Happy to try, but I do not have broken data, could you test?
