### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by marsh-circle** [TechToThePeople/civisualize#92]
i Guys,
Extension looks good, and very useful for a lot of people - thanks :)
I know this isn't a tech question, but where do I start to create visual reports on their own - so I have to code each pie chart to see them? and do they each go on their own site page?
Sorry for asking what is probably a stupid question, but I don't really see how to get started with making this work on a user level.

Cheers.

**Comment by tttp** [comment]
Hey,

Not sure what you want to do, but check the readme, it should be clear about how to create your custom graphs

the idea is that you create a new templates/dataviz/Whatever.tpl where you put the few lines of js needed to make a graph

and you can then simply access it from /civicrm/dataviz/whatever

does it help?
