### ISSUE TITLE
Events dataviz dashlet bug and breaking dashboard

### ISSUE THREAD

**Issue by gobnat** [TechToThePeople/civisualize#93]
This is happening

![dashlet-dataviz](https://user-images.githubusercontent.com/2560107/48097790-f0db8b80-e26e-11e8-9d3d-73119f003189.png)

It also then breaks the dashboard configuration screen as follows:

![dashboard-config](https://user-images.githubusercontent.com/2560107/48097941-60517b00-e26f-11e8-8c09-adca0bbecdb1.png)

It is not possible to select, move or delete anything on the above config screen.

Appears to be throwing this exception:

> dc.errors.InvalidStateException
message: "Mandatory attribute chart.group is missing on chart[#participants]"

Can only then fix by deleting the dashlet and completely reloading the page. 

Error originally occured on a new civi install with no events but the problem persisted even after events were created and participants added to the events. 

Using CiviCRM 5.3

**Comment by tttp** [comment]
It should be fixed on the latest version (just changed)
