### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by TechnologyClassroom** [TechToThePeople/civisualize#97]
There is no LICENSE or COPYING file for this project.  I see the [info.xml](https://github.com/TechToThePeople/civisualize/blob/43e6a674ac5ef0e57b6bcd9db1e49f125cdded5a/info.xml) file and https://github.com/TechToThePeople/civisualize/issues/66 indicates the license is AGPL.

If you would like me to submit a PR to make this easier, I would be happy to do that.

**Comment by wmortada** [comment]
We've now got two license notices! I've removed the second one with #106
